if(EXISTS "/Users/shree/Downloads/lms-master/src/libs/utils/test/test-utils[1]_tests.cmake")
  include("/Users/shree/Downloads/lms-master/src/libs/utils/test/test-utils[1]_tests.cmake")
else()
  add_test(test-utils_NOT_BUILT test-utils_NOT_BUILT)
endif()
