add_test([=[EnumSet.ctr]=]  /Users/shree/Downloads/lms-master/src/libs/utils/test/test-utils [==[--gtest_filter=EnumSet.ctr]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EnumSet.ctr]=]  PROPERTIES WORKING_DIRECTORY /Users/shree/Downloads/lms-master/src/libs/utils/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RecursiveSharedMutex.SingleThreaded]=]  /Users/shree/Downloads/lms-master/src/libs/utils/test/test-utils [==[--gtest_filter=RecursiveSharedMutex.SingleThreaded]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RecursiveSharedMutex.SingleThreaded]=]  PROPERTIES WORKING_DIRECTORY /Users/shree/Downloads/lms-master/src/libs/utils/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RecursiveSharedMutex.MultiThreaded]=]  /Users/shree/Downloads/lms-master/src/libs/utils/test/test-utils [==[--gtest_filter=RecursiveSharedMutex.MultiThreaded]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RecursiveSharedMutex.MultiThreaded]=]  PROPERTIES WORKING_DIRECTORY /Users/shree/Downloads/lms-master/src/libs/utils/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[StringUtils.splitString]=]  /Users/shree/Downloads/lms-master/src/libs/utils/test/test-utils [==[--gtest_filter=StringUtils.splitString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[StringUtils.splitString]=]  PROPERTIES WORKING_DIRECTORY /Users/shree/Downloads/lms-master/src/libs/utils/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[StringUtils.splitStringCopy]=]  /Users/shree/Downloads/lms-master/src/libs/utils/test/test-utils [==[--gtest_filter=StringUtils.splitStringCopy]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[StringUtils.splitStringCopy]=]  PROPERTIES WORKING_DIRECTORY /Users/shree/Downloads/lms-master/src/libs/utils/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[StringUtils.escapeJSString]=]  /Users/shree/Downloads/lms-master/src/libs/utils/test/test-utils [==[--gtest_filter=StringUtils.escapeJSString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[StringUtils.escapeJSString]=]  PROPERTIES WORKING_DIRECTORY /Users/shree/Downloads/lms-master/src/libs/utils/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[StringUtils.escapeJsonString]=]  /Users/shree/Downloads/lms-master/src/libs/utils/test/test-utils [==[--gtest_filter=StringUtils.escapeJsonString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[StringUtils.escapeJsonString]=]  PROPERTIES WORKING_DIRECTORY /Users/shree/Downloads/lms-master/src/libs/utils/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[StringUtils.escapeString]=]  /Users/shree/Downloads/lms-master/src/libs/utils/test/test-utils [==[--gtest_filter=StringUtils.escapeString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[StringUtils.escapeString]=]  PROPERTIES WORKING_DIRECTORY /Users/shree/Downloads/lms-master/src/libs/utils/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[StringUtils.readAs]=]  /Users/shree/Downloads/lms-master/src/libs/utils/test/test-utils [==[--gtest_filter=StringUtils.readAs]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[StringUtils.readAs]=]  PROPERTIES WORKING_DIRECTORY /Users/shree/Downloads/lms-master/src/libs/utils/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[StringUtils.capitalize]=]  /Users/shree/Downloads/lms-master/src/libs/utils/test/test-utils [==[--gtest_filter=StringUtils.capitalize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[StringUtils.capitalize]=]  PROPERTIES WORKING_DIRECTORY /Users/shree/Downloads/lms-master/src/libs/utils/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Stringutils.date]=]  /Users/shree/Downloads/lms-master/src/libs/utils/test/test-utils [==[--gtest_filter=Stringutils.date]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Stringutils.date]=]  PROPERTIES WORKING_DIRECTORY /Users/shree/Downloads/lms-master/src/libs/utils/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Stringutils.dateTime]=]  /Users/shree/Downloads/lms-master/src/libs/utils/test/test-utils [==[--gtest_filter=Stringutils.dateTime]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Stringutils.dateTime]=]  PROPERTIES WORKING_DIRECTORY /Users/shree/Downloads/lms-master/src/libs/utils/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test-utils_TESTS EnumSet.ctr RecursiveSharedMutex.SingleThreaded RecursiveSharedMutex.MultiThreaded StringUtils.splitString StringUtils.splitStringCopy StringUtils.escapeJSString StringUtils.escapeJsonString StringUtils.escapeString StringUtils.readAs StringUtils.capitalize Stringutils.date Stringutils.dateTime)
